In [1]:
import yfinance as yf
import pandas as pd
import os
from datetime import datetime

In [2]:
START_DATE = "2005-01-01"
END_DATE = datetime.today().strftime("%Y-%m-%d")

In [11]:
stocks = pd.read_csv(r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv")
print(stocks.head())
print(f"Total Stocks: {len(stocks)}")

        Ticker                    Company  Sector
0  RELIANCE.NS        Reliance Industries  Energy
1       TCS.NS  Tata Consultancy Services      IT
2      INFY.NS                    Infosys      IT
3   HCLTECH.NS           HCL Technologies      IT
4     WIPRO.NS                      Wipro      IT
Total Stocks: 101

In [12]:
RAW_DATA_PATH = r"D:\projects\AI-Stock-Analytics-System\data\raw"
successful_downloads = []
failed_downloads = []
for ticker in stock_list:
    try:
        print(f"Downloading {ticker}...")
        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            progress=False
        )
        if df.empty:
            print(f"No data found for {ticker}")
            failed_downloads.append(ticker)
            continue
        file_name = ticker.replace(".NS", "") + ".csv"
        df.to_csv(os.path.join(RAW_DATA_PATH, file_name))
        successful_downloads.append(ticker)
        print(f"Saved {file_name}")
    except Exception as e:
        print(f"Error downloading {ticker}: {e}")
        failed_downloads.append(ticker)

Downloading RELIANCE.NS...
Saved RELIANCE.csv
Downloading TCS.NS...
Saved TCS.csv
Downloading INFY.NS...
Saved INFY.csv
Downloading SBIN.NS...
Saved SBIN.csv
Downloading ITC.NS...
Saved ITC.csv

In [13]:
print(len(stock_list))
print(stock_list[:10])
print(stock_list[-10:])

5
['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'SBIN.NS', 'ITC.NS']
['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'SBIN.NS', 'ITC.NS']

In [10]:
import os

file_path = r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv"

print("Reading from:", os.path.abspath(file_path))

stocks = pd.read_csv(file_path)

print(stocks.shape)
print(stocks.tail())

Reading from: D:\projects\AI-Stock-Analytics-System\data\stock_list.csv
(101, 3)
            Ticker                    Company   Sector
96     CHOLAFIN.NS      Cholamandalam Finance  Finance
97   SHRIRAMFIN.NS            Shriram Finance  Finance
98   MUTHOOTFIN.NS            Muthoot Finance  Finance
99       RECLTD.NS                        REC  Finance
100         PFC.NS  Power Finance Corporation  Finance

In [14]:
stocks = pd.read_csv(r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv")

stock_list = stocks["Ticker"].tolist()

print(len(stock_list))

101

In [15]:
print(stock_list[:5])
print(stock_list[-5:])

['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HCLTECH.NS', 'WIPRO.NS']
['CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'MUTHOOTFIN.NS', 'RECLTD.NS', 'PFC.NS']

In [21]:
RAW_DATA_PATH = r"D:\projects\AI-Stock-Analytics-System\data\raw"

successful_downloads = []
failed_downloads = []

for i, ticker in enumerate(stock_list, start=1):

    file_name = ticker.replace(".NS", "") + ".csv"
    file_path = os.path.join(RAW_DATA_PATH, file_name)

    # Skip if file already exists
    if os.path.exists(file_path):
        print(f"[{i}/{len(stock_list)}] {file_name} already exists. Skipping...")
        continue

    try:
        print(f"[{i}/{len(stock_list)}] Downloading {ticker}...")

        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            progress=False
        )

        if df.empty:
            print(f"No data found for {ticker}")
            failed_downloads.append(ticker)
            continue

        df.to_csv(file_path)

        successful_downloads.append(ticker)

        print(f"Saved {file_name}")

    except Exception as e:
        print(f"Error downloading {ticker}: {e}")
        failed_downloads.append(ticker)

$LTIM.NS: possibly delisted; no timezone found

1 Failed download:
['LTIM.NS']: possibly delisted; no timezone found
$TATAMOTORS.NS: possibly delisted; no timezone found

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no timezone found
$ZOMATO.NS: possibly delisted; no timezone found

1 Failed download:
['ZOMATO.NS']: possibly delisted; no timezone found

[1/101] RELIANCE.csv already exists. Skipping...
[2/101] TCS.csv already exists. Skipping...
[3/101] INFY.csv already exists. Skipping...
[4/101] HCLTECH.csv already exists. Skipping...
[5/101] WIPRO.csv already exists. Skipping...
[6/101] TECHM.csv already exists. Skipping...
[7/101] Downloading LTIM.NS...
No data found for LTIM.NS
[8/101] PERSISTENT.csv already exists. Skipping...
[9/101] COFORGE.csv already exists. Skipping...
[10/101] MPHASIS.csv already exists. Skipping...
[11/101] SBIN.csv already exists. Skipping...
[12/101] HDFCBANK.csv already exists. Skipping...
[13/101] ICICIBANK.csv already exists. Skipping...
[14/101] AXISBANK.csv already exists. Skipping...
[15/101] KOTAKBANK.csv already exists. Skipping...
[16/101] INDUSINDBK.csv already exists. Skipping...
[17/101] BANKBARODA.csv already exists. Skipping...
[18/101] PNB.csv already exists. Skipping...
[19/101] CANBK.csv already exists. Skipping...
[20/101] UNIONBANK.csv already exists. Skipping...
[21/101] ITC.csv already exists. Skipping...
[22/101] HINDUNILVR.csv already exists. Skipping...
[23/101] NESTLEIND.csv already exists. Skipping...
[24/101] BRITANNIA.csv already exists. Skipping...
[25/101] DABUR.csv already exists. Skipping...
[26/101] MARICO.csv already exists. Skipping...
[27/101] GODREJCP.csv already exists. Skipping...
[28/101] COLPAL.csv already exists. Skipping...
[29/101] TATACONSUM.csv already exists. Skipping...
[30/101] UBL.csv already exists. Skipping...
[31/101] SUNPHARMA.csv already exists. Skipping...
[32/101] DRREDDY.csv already exists. Skipping...
[33/101] CIPLA.csv already exists. Skipping...
[34/101] LUPIN.csv already exists. Skipping...
[35/101] AUROPHARMA.csv already exists. Skipping...
[36/101] TORNTPHARM.csv already exists. Skipping...
[37/101] ALKEM.csv already exists. Skipping...
[38/101] ZYDUSLIFE.csv already exists. Skipping...
[39/101] BIOCON.csv already exists. Skipping...
[40/101] DIVISLAB.csv already exists. Skipping...
[41/101] Downloading TATAMOTORS.NS...
No data found for TATAMOTORS.NS
[42/101] M&M.csv already exists. Skipping...
[43/101] MARUTI.csv already exists. Skipping...
[44/101] BAJAJ-AUTO.csv already exists. Skipping...
[45/101] HEROMOTOCO.csv already exists. Skipping...
[46/101] EICHERMOT.csv already exists. Skipping...
[47/101] TVSMOTOR.csv already exists. Skipping...
[48/101] ASHOKLEY.csv already exists. Skipping...
[49/101] BALKRISIND.csv already exists. Skipping...
[50/101] BOSCHLTD.csv already exists. Skipping...
[51/101] LT.csv already exists. Skipping...
[52/101] ULTRACEMCO.csv already exists. Skipping...
[53/101] GRASIM.csv already exists. Skipping...
[54/101] SHREECEM.csv already exists. Skipping...
[55/101] AMBUJACEM.csv already exists. Skipping...
[56/101] ACC.csv already exists. Skipping...
[57/101] DLF.csv already exists. Skipping...
[58/101] LODHA.csv already exists. Skipping...
[59/101] NBCC.csv already exists. Skipping...
[60/101] IRB.csv already exists. Skipping...
[61/101] BHARTIARTL.csv already exists. Skipping...
[62/101] IDEA.csv already exists. Skipping...
[63/101] INDUSTOWER.csv already exists. Skipping...
[64/101] POWERGRID.csv already exists. Skipping...
[65/101] NTPC.csv already exists. Skipping...
[66/101] NHPC.csv already exists. Skipping...
[67/101] ADANIPOWER.csv already exists. Skipping...
[68/101] TATAPOWER.csv already exists. Skipping...
[69/101] JSWENERGY.csv already exists. Skipping...
[70/101] TORNTPOWER.csv already exists. Skipping...
[71/101] ONGC.csv already exists. Skipping...
[72/101] BPCL.csv already exists. Skipping...
[73/101] IOC.csv already exists. Skipping...
[74/101] HINDPETRO.csv already exists. Skipping...
[75/101] OIL.csv already exists. Skipping...
[76/101] GAIL.csv already exists. Skipping...
[77/101] PETRONET.csv already exists. Skipping...
[78/101] TATASTEEL.csv already exists. Skipping...
[79/101] JSWSTEEL.csv already exists. Skipping...
[80/101] HINDALCO.csv already exists. Skipping...
[81/101] JINDALSTEL.csv already exists. Skipping...
[82/101] SAIL.csv already exists. Skipping...
[83/101] NMDC.csv already exists. Skipping...
[84/101] VEDL.csv already exists. Skipping...
[85/101] COALINDIA.csv already exists. Skipping...
[86/101] ADANIPORTS.csv already exists. Skipping...
[87/101] CONCOR.csv already exists. Skipping...
[88/101] Downloading ZOMATO.NS...
No data found for ZOMATO.NS
[89/101] PAYTM.csv already exists. Skipping...
[90/101] NYKAA.csv already exists. Skipping...
[91/101] IRCTC.csv already exists. Skipping...
[92/101] IRFC.csv already exists. Skipping...
[93/101] INDIGO.csv already exists. Skipping...
[94/101] DMART.csv already exists. Skipping...
[95/101] BAJFINANCE.csv already exists. Skipping...
[96/101] BAJAJFINSV.csv already exists. Skipping...
[97/101] CHOLAFIN.csv already exists. Skipping...
[98/101] SHRIRAMFIN.csv already exists. Skipping...
[99/101] MUTHOOTFIN.csv already exists. Skipping...
[100/101] RECLTD.csv already exists. Skipping...
[101/101] PFC.csv already exists. Skipping...

In [17]:
print(f"Downloaded: {len(successful_downloads)}")
print(f"Failed: {len(failed_downloads)}")

Downloaded: 93
Failed: 3

In [19]:
for ticker in failed_downloads:
    print(f"Retrying {ticker}")

    df = yf.download(
        ticker,
        start=START_DATE,
        end=END_DATE,
        progress=False
    )

    print(df.head())

$LTIM.NS: possibly delisted; no timezone found

1 Failed download:
['LTIM.NS']: possibly delisted; no timezone found
$TATAMOTORS.NS: possibly delisted; no timezone found

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no timezone found
$ZOMATO.NS: possibly delisted; no timezone found

1 Failed download:
['ZOMATO.NS']: possibly delisted; no timezone found

Retrying LTIM.NS
Empty DataFrame
Columns: [(Adj Close, LTIM.NS), (Close, LTIM.NS), (High, LTIM.NS), (Low, LTIM.NS), (Open, LTIM.NS), (Volume, LTIM.NS)]
Index: []
Retrying TATAMOTORS.NS
Empty DataFrame
Columns: [(Adj Close, TATAMOTORS.NS), (Close, TATAMOTORS.NS), (High, TATAMOTORS.NS), (Low, TATAMOTORS.NS), (Open, TATAMOTORS.NS), (Volume, TATAMOTORS.NS)]
Index: []
Retrying ZOMATO.NS
Empty DataFrame
Columns: [(Adj Close, ZOMATO.NS), (Close, ZOMATO.NS), (High, ZOMATO.NS), (Low, ZOMATO.NS), (Open, ZOMATO.NS), (Volume, ZOMATO.NS)]
Index: []

In [20]:
for ticker in failed_downloads:
    print(f"Retrying {ticker}")

    df = yf.download(
        ticker,
        start=START_DATE,
        end=END_DATE,
        progress=False
    )

    print(df.head())

$LTIM.NS: possibly delisted; no timezone found

1 Failed download:
['LTIM.NS']: possibly delisted; no timezone found
$TATAMOTORS.NS: possibly delisted; no timezone found

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no timezone found
$ZOMATO.NS: possibly delisted; no timezone found

1 Failed download:
['ZOMATO.NS']: possibly delisted; no timezone found

Retrying LTIM.NS
Empty DataFrame
Columns: [(Adj Close, LTIM.NS), (Close, LTIM.NS), (High, LTIM.NS), (Low, LTIM.NS), (Open, LTIM.NS), (Volume, LTIM.NS)]
Index: []
Retrying TATAMOTORS.NS
Empty DataFrame
Columns: [(Adj Close, TATAMOTORS.NS), (Close, TATAMOTORS.NS), (High, TATAMOTORS.NS), (Low, TATAMOTORS.NS), (Open, TATAMOTORS.NS), (Volume, TATAMOTORS.NS)]
Index: []
Retrying ZOMATO.NS
Empty DataFrame
Columns: [(Adj Close, ZOMATO.NS), (Close, ZOMATO.NS), (High, ZOMATO.NS), (Low, ZOMATO.NS), (Open, ZOMATO.NS), (Volume, ZOMATO.NS)]
Index: []

In [22]:
import os

raw_path = r"D:\projects\AI-Stock-Analytics-System\data\raw"

csv_files = [f for f in os.listdir(raw_path) if f.endswith(".csv")]

print("Total CSV files:", len(csv_files))

Total CSV files: 98

In [23]:
stocks[stocks["Ticker"].str.contains("ZOMATO|ETERNAL", na=False)]

       Ticker Company         Sector
87  ZOMATO.NS  Zomato  Consumer Tech

In [25]:
import os

print(os.path.abspath(file_path))

D:\projects\AI-Stock-Analytics-System\data\raw\PFC.csv

In [26]:
import os

print(file_path)
print(os.path.exists(file_path))

D:\projects\AI-Stock-Analytics-System\data\raw\PFC.csv
True

In [27]:
stocks = pd.read_csv(file_path)

print(stocks.iloc[87])

Price             2007-06-28
Close     24.248424530029297
High      24.876750757127276
Low        23.42167974335678
Open       23.81024922541227
Volume              17936450
Name: 87, dtype: object

In [28]:
import os

for root, dirs, files in os.walk(r"D:\projects\AI-Stock-Analytics-System"):
    for file in files:
        if file == "stock_list.csv":
            print(os.path.join(root, file))

D:\projects\AI-Stock-Analytics-System\data\stock_list.csv

In [29]:
print(file_path)

D:\projects\AI-Stock-Analytics-System\data\raw\PFC.csv

In [30]:
print(os.getcwd())

D:\projects\AI-Stock-Analytics-System\notebooks

In [31]:
stock_list_path = r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv"

stocks = pd.read_csv(stock_list_path)

print(stocks.loc[87])

Ticker           NYKAA.NS
Company    FSN E-Commerce
Sector      Consumer Tech
Name: 87, dtype: object

In [32]:
stocks[stocks["Ticker"].str.contains("ETERNAL|ZOMATO", na=False)]

        Ticker Company         Sector
85  ETERNAL.NS  Zomato  Consumer Tech

In [33]:
stock_list_path = r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv"
raw_data_path = r"D:\projects\AI-Stock-Analytics-System\data\raw"

# Inside the download loop
csv_path = os.path.join(raw_data_path, file_name)

In [34]:
import os

raw_path = r"D:\projects\AI-Stock-Analytics-System\data\raw"

csv_files = [f for f in os.listdir(raw_path) if f.endswith(".csv")]

print(f"Total CSV files: {len(csv_files)}")

Total CSV files: 98

In [35]:
import os

raw_path = r"D:\projects\AI-Stock-Analytics-System\data\raw"

print(os.path.exists(os.path.join(raw_path, "ETERNAL.csv")))

False

In [36]:
import yfinance as yf
import os

ticker = "ETERNAL.NS"

df = yf.download(
    ticker,
    start=START_DATE,
    end=END_DATE,
    progress=False
)

print(df.head())

if not df.empty:
    df.to_csv(r"D:\projects\AI-Stock-Analytics-System\data\raw\ETERNAL.csv")
    print("ETERNAL.csv saved successfully!")
else:
    print("No data downloaded.")

Price            Close        High         Low        Open     Volume
Ticker      ETERNAL.NS  ETERNAL.NS  ETERNAL.NS  ETERNAL.NS ETERNAL.NS
Date
2021-07-23  126.000000  138.899994  115.000000  116.000000  694895290
2021-07-26  140.649994  143.750000  125.300003  126.349998  249723854
2021-07-27  132.899994  147.800003  127.750000  141.699997  240341900
2021-07-28  131.199997  135.000000  123.550003  131.000000  159793731
2021-07-29  141.550003  144.000000  132.199997  134.949997  117973089
ETERNAL.csv saved successfully!

In [37]:
import os

csv_files = [f for f in os.listdir(r"D:\projects\AI-Stock-Analytics-System\data\raw") if f.endswith(".csv")]

print("Total CSV files:", len(csv_files))

Total CSV files: 99

In [38]:
import pandas as pd

stock_list_path = r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv"

stocks = pd.read_csv(stock_list_path)
stock_list = stocks["Ticker"].tolist()

print(len(stock_list))
print(stock_list[-15:])

101
['PAYTM.NS', 'NYKAA.NS', 'IRCTC.NS', 'IRFC.NS', 'INDIGO.NS', 'DMART.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'MUTHOOTFIN.NS', 'RECLTD.NS', 'PFC.NS', 'PERSISTENT.NS', 'ASHOKLEY.NS']

In [40]:
import yfinance as yf
import os

RAW_DATA_PATH = r"D:\projects\AI-Stock-Analytics-System\data\raw"

new_tickers = [
    "PERSISTENT.NS",
    "ASHOKLEY.NS",
    "ETERNAL.NS"
]

for ticker in new_tickers:

    print(f"\nDownloading {ticker}...")

    df = yf.download(
        ticker,
        start=START_DATE,
        end=END_DATE,
        progress=False
    )

    if df.empty:
        print(f"Failed: {ticker}")
        continue

    file_name = ticker.replace(".NS", "") + ".csv"
    save_path = os.path.join(RAW_DATA_PATH, file_name)

    df.to_csv(save_path)

    print(f"Saved {file_name}")

Downloading PERSISTENT.NS...
Saved PERSISTENT.csv

Downloading ASHOKLEY.NS...
Saved ASHOKLEY.csv

Downloading ETERNAL.NS...
Saved ETERNAL.csv

In [41]:
import pandas as pd

stock_list_path = r"D:\projects\AI-Stock-Analytics-System\data\stock_list.csv"

stocks = pd.read_csv(stock_list_path)
stock_list = stocks["Ticker"].tolist()

print("Total Stocks:", len(stock_list))
print("Unique Stocks:", stocks["Ticker"].nunique())

Total Stocks: 101
Unique Stocks: 101

In [44]:
new_tickers = [
    "BHEL.NS",
    "POLYCAB.NS"
]

for ticker in new_tickers:

    print(f"Downloading {ticker}...")

    df = yf.download(
        ticker,
        start=START_DATE,
        end=END_DATE,
        progress=False
    )

    if df.empty:
        print(f"❌ Failed: {ticker}")
    else:
        df.to_csv(
            os.path.join(RAW_DATA_PATH, ticker.replace(".NS", "") + ".csv")
        )
        print(f"✅ Saved {ticker}")

Downloading BHEL.NS...
✅ Saved BHEL.NS
Downloading POLYCAB.NS...
✅ Saved POLYCAB.NS

In [45]:
csv_files = [f for f in os.listdir(RAW_DATA_PATH) if f.endswith(".csv")]

print("CSV Files:", len(csv_files))

CSV Files: 101